name: Run jobs on release tags when pushed

on: 
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:
  build-release-variant:
    runs-on: macOS-10.14
    steps:
    - run: echo 'todo'